package rules

import (
	"github.com/Yakitori197/yolab-agent-skill-guard/internal/model"
	"github.com/Yakitori197/yolab-agent-skill-guard/internal/parser"
)

// ASG900 — Expired Suppression. This is a governance meta-rule: its findings
// are generated by the engine from configuration state, not from document
// content, so Check is a no-op. It cannot be disabled.
type asg900 struct{}

var asg900Meta = model.RuleMeta{
	ID:              "ASG900",
	Title:           "Expired Suppression",
	Summary:         "A configured suppression has lapsed and no longer silences its finding.",
	DefaultSeverity: model.SeverityInfo,
	Category:        "governance",
	Heuristic:       false,
	Rationale: "Suppressions are temporary, reasoned exceptions. Once the expiry date passes, the exception " +
		"must be re-reviewed: either the underlying finding is fixed (delete the suppression) or the " +
		"justification still holds (extend the expiry consciously). Silent indefinite continuation is exactly what expiries prevent.",
	Remediation: "Remove the expired suppression if the finding is resolved, or set a new expiry with an " +
		"updated reason after review.",
	SafeExample:   "A suppression with a future expiry and a concrete reason.",
	UnsafeExample: "A suppression whose expiry passed months ago, still sitting in the config.",
	Contexts:      []string{"config"},
}

func (asg900) Meta() model.RuleMeta { return asg900Meta }

func (asg900) Check(_ *parser.Document, _ *Context) []model.Finding { return nil }
